services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WITCH_PORT=8080
      - WITCH_HOST=
    ports:
      - "5001:5001"
  
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - C:\Users\spaul\projects\witch\local_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
